# DISCLAIMER: 
# This file is provided "AS IS" and is intended solely for illustrative or educational purposes. 
# Domotz makes no warranties, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. Use of this file is at your own risk. 
# By using this file, you acknowledge and agree that Domotz shall not be liable for any direct, indirect, incidental, or consequential damages or losses arising from its use.  
# You further agree to indemnify, defend, and hold harmless Domotz and its affiliates from and against any claims, liabilities, damages, or expenses resulting from your use or misuse of this file. 
#
# In the event of any conflict between this disclaimer and any other agreement between you and Domotz, this disclaimer shall prevail with respect to the use of this file. 
#
# Domotz Netplan - Static ip address
# the NIC name has to be edited with yours - you can find it by using the issuing 'sudo ifconfig' or 'ip a'
network:
    version: 2
    ethernets:
        ens160: # NIC name - to be changed (replace ens160 with your NIC name)
            dhcp6: false
            dhcp4: false
            addresses: [192.168.1.250/24] # change with the right static ip address of the Domotz Agent followed by subnet mask in / format
            gateway4: 192.168.1.1 # change with the gatway address of your network
            nameservers: 
                addresses: [ "8.8.8.8", "1.1.1.1" ]
    vlans:
        vlan2:
            id: 2
            link: ens160 # change the NIC name also here
            addresses: [ "192.168.2.250/24" ] # change with the right static ip address of the Domotz Agent in this VLAN followed by subnet mask in / format
        vlan6:
            id: 3
            link: ens160  # change the NIC name also here
            addresses: [ "192.168.3.250/24" ] # change with the right static ip address of the Domotz Agent on this VLAN followed by subnet mask in / format